import * as cdk from 'aws-cdk-lib';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface SecretsStackProps extends cdk.StackProps {
  envName: string;
}

/**
 * SecretsStack — application-level secrets not auto-generated by AWS.
 *
 * After first deploy, populate this secret manually in the AWS console or CLI:
 *   JWT_SECRET, MUX_TOKEN_ID, MUX_TOKEN_SECRET, POSTHOG_API_KEY, SENTRY_DSN
 *
 * ECS task role in ComputeStack is granted read access to this secret.
 * Database credentials live separately in DataStack's DatabaseSecret.
 */
export class SecretsStack extends cdk.Stack {
  readonly appSecrets: secretsmanager.ISecret;

  constructor(scope: Construct, id: string, props: SecretsStackProps) {
    super(scope, id, props);

    this.appSecrets = new secretsmanager.Secret(this, 'AppSecrets', {
      secretName: `bloc/${props.envName}/app`,
      description: 'Application secrets for Bloc backend',
    });

    new cdk.CfnOutput(this, 'AppSecretsArn', {
      value: this.appSecrets.secretArn,
    });
  }
}
